# Generated by Django 6.0.3 on 2026-03-19 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('scientific_name', models.CharField(blank=True, max_length=200)),
                ('local_language', models.CharField(blank=True, max_length=100)),
                ('geographic_distribution', models.TextField(blank=True)),
                ('ailments_treated', models.TextField()),
                ('preparation_method', models.TextField()),
                ('dosage', models.TextField()),
                ('side_effects', models.TextField(blank=True)),
                ('cultural_significance', models.TextField(blank=True)),
                ('cultivation_notes', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='plants/')),
                ('audio_file', models.FileField(blank=True, upload_to='audio/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
