# Generated by Django 6.0.6 on 2026-07-28 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0002_rename_ailments_treated'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='plant',
            options={'ordering': ['name']},
        ),
        migrations.AddField(
            model_name='plant',
            name='approval_status',
            field=models.CharField(choices=[('pending', 'Pending Approval'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', help_text='Approval status for the knowledge validation workflow', max_length=20),
        ),
        migrations.AddField(
            model_name='plant',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='plant',
            name='approved_by',
            field=models.ForeignKey(blank=True, help_text='Administrator who approved this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='body_system',
            field=models.CharField(blank=True, help_text='Body system primarily affected (e.g., digestive, respiratory, circulatory)', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='contraindications',
            field=models.TextField(blank=True, help_text='Situations where the herbal remedy should not be administered'),
        ),
        migrations.AddField(
            model_name='plant',
            name='harvesting_season',
            field=models.CharField(blank=True, help_text='The appropriate time for collecting herbal materials for maximum medicinal effectiveness', max_length=200),
        ),
        migrations.AddField(
            model_name='plant',
            name='plant_family',
            field=models.CharField(blank=True, help_text='Botanical family (e.g., Fabaceae, Asteraceae, Lamiaceae, Rutaceae)', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='submitted_by',
            field=models.ForeignKey(blank=True, help_text='User who submitted this plant record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='submitted_plants', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='plant',
            name='treatment_category',
            field=models.CharField(blank=True, help_text='Therapeutic property (e.g., antimalarial, antibacterial, anti-inflammatory)', max_length=100),
        ),
        migrations.AddField(
            model_name='plant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='plant',
            name='audio_file',
            field=models.FileField(blank=True, help_text='Audio recording of traditional knowledge', upload_to='audio/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='cultivation_notes',
            field=models.TextField(blank=True, help_text='How the plant is grown or harvested'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='cultural_significance',
            field=models.TextField(blank=True, help_text='Traditional significance, cultural practices, beliefs, rituals'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='disease_cured',
            field=models.TextField(help_text='Disease or health condition treated'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='dosage',
            field=models.TextField(help_text='Recommended dosage, frequency, and duration'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='geographic_distribution',
            field=models.TextField(blank=True, help_text='Where the plant is found'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='image',
            field=models.ImageField(blank=True, help_text='Image of the medicinal plant', upload_to='plants/'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='local_language',
            field=models.CharField(blank=True, help_text='Local name in indigenous language', max_length=100),
        ),
        migrations.AlterField(
            model_name='plant',
            name='name',
            field=models.CharField(help_text='Common/plant name', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='preparation_method',
            field=models.TextField(help_text='Method of preparation (decoction, infusion, powder, paste, extract)'),
        ),
        migrations.AlterField(
            model_name='plant',
            name='scientific_name',
            field=models.CharField(blank=True, help_text='Scientific/botanical name', max_length=200),
        ),
        migrations.AlterField(
            model_name='plant',
            name='side_effects',
            field=models.TextField(blank=True, help_text='Possible side effects or contraindications'),
        ),
    ]
