# Generated by Django 6.0.3 on 2026-07-30 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0003_alter_plant_options_plant_approval_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='plant',
            name='document_file',
            field=models.FileField(blank=True, help_text='PDF or document reference', upload_to='documents/'),
        ),
        migrations.AddField(
            model_name='plant',
            name='video_file',
            field=models.FileField(blank=True, help_text='Video documentation of preparation or use', upload_to='videos/'),
        ),
    ]
