# Generated by Django 6.0.6 on 2026-07-28 18:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('administrator', 'Administrator'), ('traditional_health_practitioner', 'Traditional Health Practitioner'), ('researcher', 'Researcher'), ('community_member', 'Community Member')], default='community_member', help_text="User's role determines their access level and permissions.", max_length=50)),
                ('phone_number', models.CharField(blank=True, max_length=20)),
                ('specialization', models.CharField(blank=True, help_text='For practitioners: area of expertise', max_length=200)),
                ('organization', models.CharField(blank=True, help_text='Institution or community', max_length=200)),
                ('bio', models.TextField(blank=True, help_text='Brief biography or description')),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='profiles/')),
                ('is_approved', models.BooleanField(default=True, help_text='Whether the user account is approved for use')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'User Profile',
                'verbose_name_plural': 'User Profiles',
            },
        ),
    ]
