# Generated by Django 6.0.3 on 2026-03-23 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('transcription', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transcription',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='transcriptions/'),
        ),
    ]
